### ISSUE TITLE
Updating to 3.00 release broke radarr on my Raspberry Pi

### ISSUE THREAD

**Issue by joopdehoop** [docker-hotio/docker-radarr#18]
I was running hotio/radarr with Radarr 0.2.0 on my rpi just fine until I upgraded to the image with Radarr 3.00 release yesterday. Ever since, the container is unable to have any connectivity, to other containers, my lan, let alone internet. Nightly version isn't working for me either. Downgrading back to release-0.2.0.1504 fixed it for me. 

I should note I also tried the 3.00 Radarr container by Linuxserver, had the same issue.

**Comment by hotio** [comment]
Most likely a problem with your host os...see https://docs.linuxserver.io/faq for more info.
